[package]
name = "h_2_1"
version = "0.1.0"
edition = "2021"

[features]
default = ["el2"]
el2 = ["axhal/el2", "axmm/el2"]

[dependencies]
axstd = { workspace = true, features = ["alloc", "paging", "fs", "multitask", "irq"] }
axhal = { workspace = true }
axmm = { workspace = true }
aarch64_vcpu = { path = "../../modules/aarch64_vcpu" }
axerrno = "0.1"
memory_addr = "0.3"
axlog = { workspace = true }
